name: SSR Support
description: 'Check if the app supports SSR'
runs:
  using: "composite"
  steps:
    - name: Link package
      shell: bash
      run: npm link
    - name: Create SSR app with nextjs pages dir (< 13)
      shell: bash
      run: |
        cd ..
        npx create-next-app@12 ssr-app --typescript
        cd ssr-app
        npm i baseui styletron-engine-atomic styletron-react
        npm link @nilfoundation/ui-kit
    - name: Create starter app
      shell: bash
      working-directory: ../ssr-app
      run: |
        echo "
        import { Client, Server } from 'styletron-engine-atomic'
        const getHydrateClass = () =>
          document.getElementsByClassName('_styletron_hydrate_') as HTMLCollectionOf<HTMLStyleElement>
        export const styletron =
          typeof window === 'undefined'
            ? new Server()
            : new Client({
                hydrate: getHydrateClass(),
              })
        " > ./styletron.ts

        echo "
        import { AppProps } from 'next/app'
        import { styletron } from '../styletron'
        import { Provider as StyletronProvider } from 'styletron-react'
        import { BaseProvider } from 'baseui'
        import { createTheme } from '@nilfoundation/ui-kit'
        const MyApp = ({ Component, pageProps }: AppProps) => {
          const { theme } = createTheme(styletron)
          return (
            <StyletronProvider value={styletron}>
              <BaseProvider theme={theme}>
                <Component {...pageProps} />
              </BaseProvider>
            </StyletronProvider>
          )
        }
        export default MyApp
        " > pages/index.tsx

    - name: Build
      shell: bash
      working-directory: ../ssr-app
      run: npm run build
    - name: Cold start
      shell: bash
      working-directory: ../ssr-app
      run: |
        npm run start &
        sleep 5
        curl http://localhost:3000
        exit 0
