name: Build
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Build
      run: |
        npm run build
        ls -lh dist
    - run: npm run build:standalone
    - name: Check SSR Support
      uses: ./.github/actions/ssr-support
