name: Build

on:
  # Triggers the workflow on every pull-request
  pull_request:
  # Allows to trigger workflow manually
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: |
        npm run build
        ls -lh dist
